### ISSUE TITLE
Upgrade to Groovy 2.5

### ISSUE THREAD

**Issue by RDevet** [dwclark/http-builder-ng#197]
Groovy 2.5 has been out for while.  So please upgrade this awesome library.

**Comment by cjstehno** [comment]
Have you found it to not work with Groovy 2.5 or are there specific related features you find missing? Unless Groovy pulled a "Java 9" I would expect it work work under new Groovy language version (since the library itself is written in Java)... if there are specific issues, please add them as comments here.

I will try to poke around the library with Groovy 2.5 myself soon, but not sure when.

@dwclark have you done anything with Groovy 2.5 yet?

> If May 30th is "a while", I want to work for your company :-)
