### ISSUE TITLE
`FromServer.Header.getKeysValues()` results in odd format

### ISSUE THREAD

**Issue by cjstehno** [dwclark/http-builder-ng#9]
The `FromServer.Header.getKeysValues()` method seems to result in an odd format. See the `FromServerSpec.'Header.keysValues'` test for an example:

When the header is multi-valued, such as:

    keyValue('Forwarded', 'for=192.0.2.60;proto=http;by=203.0.113.43')

The method call results in:

```
keysValues == [
    Forwarded: [],
    by       : ['203.0.113.43'],
    for      : ['192.0.2.60'],
    proto    : ['http']
] 
```

which seems incorrect (or non-intuitive). Seems like the it should be a nested map rather than having the original header off by itself. 

Need to see how a servlet container handles multi-valued response headers to be sure.

**Comment by dwclark** [comment]
The problem with HTTP headers is that there isn't a uniform way to parse and represent them, once you get beyond key/value. The only real uniform way is to return a Map<String,String>, that will always be uniform. But, it won't be useful for so many headers because they also require further parsing. I was trying to support all of the response headers here:

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

So you have to support true key/values like this: `Accept-Ranges: bytes`

And CSV lists like this: `Allow: GET, HEAD`

And inconsistent key/value maps like this: `Content-Disposition: attachment; filename="fname.ext"`

And stuff that should be de-quoted like this: `ETag: "737060cd8c284d8af7ad3082f209582d"`

And key value pairs that are semi-colon separated like this: `Public-Key-Pins: max-age=2592000; pin-sha256="E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=";`

And there are probably others. I gave up and punted once I saw that Apache Http Client also gives up and punts. Probably the only way to do this right is to have a registry of parsers that get executed for each header, all of which will return different types. Then it would return a Map<String,Object> and it would be up to the caller to figure out what the Object's type is and what to do with it.

The choices are basically 1) return a consistent type that is useful some of the time; 2) return an inconsistent type that is useful once you know what it is. Basic laziness forced me to 1). I'm open to changing the implementation, but it's going to be ugly no matter how we slice it.

**Comment by dwclark** [comment]
OK, I think I have a good way of doing this. It's going to require a custom Map. I should be able to support  both the standard/regular `Map<String,String>` and a parsed format.

**Comment by dwclark** [comment]
@cjstehno I opened a pull request called better-headers which has my proposed solution to this problem. Basically each header will be able to be parsed based on the header name. `Header.java` has all of the available parsers. There is a specific `Map` type in `Headers.java` which implements a standard `Map<String,String>` type for treating the headers as key values. It also strengthens the Map interface by providing the ability to get at the parsed versions of the headers.

Let me know if this is good and I will changed the header implementation in the Builders and move over the docs.

**Comment by cjstehno** [comment]
Yeah, this seems like a better implementation. Damn, there are quite a few different header types, nothing like consistency. :-)

**Comment by cjstehno** [comment]
This has been resolved - closing.
